version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: product_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./Back-end
    container_name: product_backend
    ports:
      - "8080:8080"
    env_file:
      - ./Back-end/.env
    depends_on:
      - db

volumes:
  pgdata:
